//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("4.1.1")]
[assembly: AssemblyFileVersion("4.1.1")]
[assembly: AssemblyInformationalVersion("4.1.1-beta.1+131")]
[assembly: AssemblyCopyright("Copyright © WildGums 2014 - 2020")]

